---
- hosts: web-servers
  tasks:
    - name: simple ping
      ping:
    
    - name: Install web Servers
      yum:
        name: httpd
        state: present

    - name: Start web servers
      service:
        name: httpd
        state: stopped
      become: true
    
    - name: Copy file to Httpd
      template: 
        src: ~/index.html
        dest: /var/www/html/index.html
        mode: '0777'
      become: true
      tags: c1

