---
# tasks file for bjss

- name: Ensure Apache is installed
  yum:
    name: httpd
    state: present

- name: Ensure Apache is enabled and started
  service:
    name: htppd
    state: started
    enabled: true

- name: Install PHP7 common packages
  yum:
    name: "{{ item }}"
  with_items:
    - mod_php71w
    - php71w-cli
    - php71w-common
    - php71w-gd
    - php71w-mbstring
    - php71w-mcrypt
    - php71w-mysqlnd
    - php71w-xml

- name: Install Rsync
  yum :
    name: rsync
    state: present

    - name: Deploy and configure CodeIgniter
      copy:
        src: /home/centos7/CodeIgniter-3.1.4/
        dest: /var/www/html/
        become: true