---
- hosts: loadbalancer
  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: removed
        update_cache: yes
      become: true

    - name: Start Nginx
      service:
        name: nginx
        state: removed
        enabled: yes
      become: true
