---
- hosts: webserver
  become: true
  vars_files:
    db_vars.yml
  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted

  pre_tasks:
    - name: Create UserGroup
      group:
        name: developers
        state: present

  post_tasks:
    - name: Changes of ownership of CodeIgniter files to be owned by cidev and developer group
      file:
        path: /var/www/html/
        owner: cidev
        group: developers
        state: directory
        recurse: yes

    - name: Create a User for the Group
      user:
        name: cidev
        group: developers
        comment: This is a  codeigniter user
        state: present

  tasks:
    - name: Install Webserver
      yum:
        name: httpd
        state: absent

    - name: Start Webserver
      service:
        name: httpd
        state: removed
        enabled: yes
      tags: tees

    - name: Install Mysql package on WebServer
      yum:
        name: mysql
        state: absent

    - name: Add Yum Repo for PHP
      yum_repository:
        name: epel
        description: Adding Repository for PHP
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
        gpgcheck: no
        state: present

    - name: Webtactic Repo
      yum_repository:
        name: webtatic
        description: Webtatic Repository
        baseurl: https://repo.webtatic.com/yum/el7/$basearch/
        gpgcheck: no
        state: present


    - name:  Install PHP7 common packages
      yum:
        name: "{{ item }}"
        state: absent
      with_items:
        - mod_php71w
        - php71w-cli
        - php71w-common
        - php71w-gd
        - php71w-mbstring
        - php71w-mcrypt
        - php71w-mysqlnd
        - php71w-xml


    - name: Ensure we have R-sync installed
      yum:
        name: rsync
        state: present

    - name: Copy CodeIgniter files
      copy:
        src: /home/centos7/CodeIgniter-3.1.4/
        dest: /var/www/html/
      become: true
      tags: tees


    - name: Ensure mode_rewrite is enabled on Apache server
      lineinfile:
        path: /etc/httpd/conf.modules.d/00-base.conf
        regexp: '^.*rewrite_module.*$'
        line: 'LoadModule rewrite_module modules/mod_rewrite.so'
        state: present
      notify:
        restart httpd

    - name: Configure the application with the database settings
      template:
        src: /home/centos7/ansibletut/templates/application/config/database.php.jn2
        dest: /var/www/html/application/config/database.php

    - name: Deploy sample CodeIgniter files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - src: /home/centos7/ansibletut/pages/models/News_model.php
          dest: /var/www/html/application/models/News_model.php
        - src: /home/centos7/ansibletut/pages/views/news_article.php
          dest: /var/www/html/application/views/news_article.php
        - src: /home/centos7/ansibletut/pages/controllers/News.php
          dest: /var/www/html/application/controllers/News.php







